name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          touch ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLIC_KEY }}"
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa "${{ secrets.IP }}" >> ~/.ssh/known_hosts

      - name: Test SSH Connection
          run: |
            ssh -i ~/.ssh/id_rsa "${{ secrets.USERNAME }}"@"${{ secrets.IP }}" echo "SSH connection successful!"

      - name: Deploy to DigitalOcean
        run: |
          ssh "${{ secrets.USERNAME }}"@"${{ secrets.IP }}" 'cd "${{ secrets.DIRECTORY }}" && git pull'

